services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"   # NATS clients
      - "8222:8222"   # Monitoring HTTP endpoint
    command: [
      "-js",
      "-m", "8222"     # включение HTTP мониторинга
    ]
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"   # Redis default port
    restart: always